enum CustomIcons {
  addMessage("assets/images/svg_add_message.svg"),
  call("assets/images/svg_call.svg"),
  chatMessage("assets/images/svg_chat_message.svg"),
  check("assets/images/svg_check.svg"),
  disappointed("assets/images/svg_disappointed.svg"),
  doNotBleach("assets/images/svg_do_not_bleach.svg"),
  doNotTumbleDry("assets/images/svg_do_not_tumble_dry.svg"),
  doNotWash("assets/images/svg_do_not_wash.svg"),
  doorToDoorDelivery("assets/images/svg_door_to_door_delivery.svg"),
  export("assets/images/svg_export.svg"),
  filter("assets/images/svg_filter.svg"),
  gallery("assets/images/svg_gallery.svg"),
  gridView("assets/images/svg_grid_view.svg"),
  happy("assets/images/svg_happy.svg"),
  inLove("assets/images/svg_in_love.svg"),
  instagramDark("assets/images/svg_instagram_dark.svg"),
  instagramLight("assets/images/svg_instagram_light.svg"),
  ironLowTemperature("assets/images/svg_iron_low_temperature.svg"),
  listview("assets/images/svg_listview.svg"),
  location("assets/images/svg_location.svg"),
  mastercard("assets/images/svg_mastercard.svg"),
  menu("assets/images/svg_menu.svg"),
  miroodlesSticker("assets/images/svg_miroodles_sticker.svg"),
  refresh("assets/images/svg_refresh.svg"),
  resize("assets/images/svg_resize.svg"),
  search("assets/images/svg_search.svg"),
  shipping("assets/images/svg_shipping.svg"),
  shoppingBag("assets/images/svg_shopping_bag.svg"),
  star("assets/images/svg_star.svg"),
  tag("assets/images/svg_tag.svg"),
  tailorsDummy("assets/images/svg_tailors_dummy.svg"),
  twitterOrange("assets/images/svg_twitter_orange.svg"),
  twitter("assets/images/svg_twitter.svg"),
  voucher("assets/images/svg_voucher.svg"),
  youtube("assets/images/svg_youtube.svg"),
  svgInstagramLight("assets/images/svg_instagram_light.svg"),

  boss("assets/images/svg_boss.svg"),
  burberry("assets/images/svg_burberry.svg"),
  catier("assets/images/svg_catier.svg"),
  gucci("assets/images/svg_gucci.svg"),
  prada("assets/images/svg_prada.svg"),
  tiffanyCo("assets/images/svg_tiffany_co.svg");

  const CustomIcons(this.path);
  final String path;
}
