enum CustomImages {
  imgPerson1("assets/images/img_person_1.png"),
  imgPerson2("assets/images/img_person_2.png"),
  imgPerson3("assets/images/img_person_3.png"),
  imgPerson4("assets/images/img_person_4.png"),
  imgPerson5("assets/images/img_person_5.png"),
  imgPerson6("assets/images/img_person_6.png"),
  imgPerson7("assets/images/img_person_7.png"),
  imgPerson8("assets/images/img_person_8.png"),
  imgPerson9("assets/images/img_person_9.png"),
  imgPerson10("assets/images/img_person_10.png"),
  imgPerson11("assets/images/img_person_11.png"),
  imgPerson12("assets/images/img_person_12.png"),
  imgPerson13("assets/images/img_person_13.png"),
  imgPerson14("assets/images/img_person_14.png"),
  imgPerson15("assets/images/img_person_15.png"),
  imgPerson16("assets/images/img_person_16.png"),
  imgPerson17("assets/images/img_person_17.png"),
  imgPerson18("assets/images/img_person_18.png"),
  imgPerson19("assets/images/img_person_19.png"),
  imgPerson20("assets/images/img_person_20.png"),
  imgPerson21("assets/images/img_person_21.png"),
  imgPerson22("assets/images/img_person_22.png"),
  imgPerson23("assets/images/img_person_23.png"),
  imgPerson24("assets/images/img_person_24.png"),
  imgPerson25("assets/images/img_person_25.png"),
  imgPerson26("assets/images/img_person_26.png"),
  imgPerson27("assets/images/img_person_27.png"),
  imgPerson28("assets/images/img_person_28.png"),
  imgPerson29("assets/images/img_person_29.png"),
  imgPerson30("assets/images/img_person_30.png"),
  imgPerson31("assets/images/img_person_31.png"),
  imgPerson32("assets/images/img_person_32.png"),
  imgPerson33("assets/images/img_person_33.png"),
  imgPerson34("assets/images/img_person_34.png"),
  imgPerson35("assets/images/img_person_35.png"),

  imgPersonStyle1("assets/images/img_person_style_1.png"),
  imgPersonStyle2("assets/images/img_person_style_2.png"),
  imgPersonStyle3("assets/images/img_person_style_3.png"),
  imgPersonStyle4("assets/images/img_person_style_4.png"),
  imgPersonStyle5("assets/images/img_person_style_5.png"),
  imgPersonStyle6("assets/images/img_person_style_6.png"),
  imgPersonStyle7("assets/images/img_person_style_7.png"),

  imgProduct1("assets/images/img_product_1.png"),
  imgProduct2("assets/images/img_product_2.png"),
  imgProduct3("assets/images/img_product_3.png"),
  imgProduct4("assets/images/img_product_4.png"),
  imgProduct5("assets/images/img_product_5.png"),
  imgProduct6("assets/images/img_product_6.png"),
  imgProduct7("assets/images/img_product_7.png"),
  imgProduct8("assets/images/img_product_8.png"),
  imgProduct9("assets/images/img_product_9.png"),
  imgProduct10("assets/images/img_product_10.png"),
  imgProduct11("assets/images/img_product_11.png"),
  imgProduct12("assets/images/img_product_12.png"),
  imgProduct13("assets/images/img_product_13.png"),
  imgProduct14("assets/images/img_product_14.png"),
  imgProduct15("assets/images/img_product_15.png"),

  imgVideo("assets/images/img_video.png"),
  imgPersonBanner("assets/images/img_person_banner.png");

  const CustomImages(this.path);
  final String path;
}
